### ISSUE TITLE
IP addresses and other factors

### ISSUE THREAD

**Issue by pjmorr** [fnerdwq/puppet-omd#1]
Is there a way to get each discovered host to include the internal IP address from ec2_local_ipv4 and add it to the clients .mk file?  It is causing grief with some of my event triggers not being able to get to that ip address.  And I have yet to find a way to add it in such a way that it sticks past another puppet run...  Otherwise, awesome project and would love to assist in adding features.

**Comment by fnerdwq** [comment]
Is there any more need here?

**Comment by pjmorr** [comment]
sorry for the delayed response.  In the AWS environment your ipaddress can sometimes be a private ip, or a public ip depending on many variables.  If you are wanting to make sure that 'monitoring' traffic stays on the internal private network then you need a reliable way to obtain that address.  In AWS this is ec2_local_ipv4 vs. ec2_public_ipv4 (also the same for ipv6).  I have since figured a workaround but wanted to make sure that I followed up with you as this is a good module.

**Comment by fnerdwq** [comment]
Thanks for the response. So closig this issue.
