### ISSUE TITLE
Agent rpm

### ISSUE THREAD

**Issue by emccormickva** [fnerdwq/puppet-omd#10]
Hello,

Given that the check_mk folks no longer provide an agent RPM, I've set the client class to not download the package. At this point it attempts to install it via yum which is great. However, it is looking for the wrong package name. It's in EPEL as check-mk-agent rather than check_mk-agent. This is the same in both EL6 and EL7 repos.

Thanks,
Erik

**Comment by fnerdwq** [comment]
Hi Erik,
oh, I didn't realize the package was also in EPEL with a different RPM package name. I should have check this before :-)

In the just now pushed master branch I added the new parameter ``package_name`` to the ``omd::client`` class, to specify the package name explicitly.

Does this solve the issue for you?

Bye
Frederik

**Comment by fnerdwq** [comment]
closed.
