### ISSUE TITLE
omd apt source should use the full fingerprint to identify your GPG keys 

### ISSUE THREAD

**Issue by jacobmw** [fnerdwq/puppet-omd#14]
omd::server::install::debian has 'F8C1CA08A57B9ED7' set as the apt repository key, but according to the  puppetlabs apt module you should use the full fingerprint:
https://github.com/puppetlabs/puppetlabs-apt/blob/master/README.md#add-gpg-keys
Using the short key causes puppet to throw warnings in the log.

**Comment by fnerdwq** [comment]
Hi,
I just updated the key to the fingerprint and prepared the modules for the usage of the puppetlabs/apt modules > v2.
