### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by SergiuCip** [fnerdwq/puppet-omd#15]
Hi,

I am getting this error message when I am trying to run puppet:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no such file to load -- puppet/util/puppetdb

Could this be because we aren't using PuppetDB?

Thank you,

Regards,
Sergiu

**Comment by fnerdwq** [comment]
Hi Sergiu,

yes, you need the PuppetDB to run this module.

Bye
Frederik
