### ISSUE TITLE
puppet > 4.0 failures

### ISSUE THREAD

**Issue by jacobmw** [fnerdwq/puppet-omd#16]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, undefined method `server' for Puppet::Util::Puppetdb:Module at /etc/puppetlabs/puppet/environments/production/modules/omd/manifests/site/config_hosts.pp:28:22

**Comment by fnerdwq** [comment]
Sorry, due to lack of time, for now no update for puppet 4+ is planned.

This error indicates a problem in the use of the dalen/puppetdbquery modules. There might be an issue with puppet 4 there. Did you install this module?

**Comment by jacobmw** [comment]
Hi Frederik,  I’m sorry to hear that you are not planning on updating the module to be compliant with puppet 4+, but I understand.
We do in fact have the dale/puppetdbquery module installed.  Perhaps I can try updating that module and see if things look better.

 
 
Jacob McCoy Wade
Systems Engineer II
510.333.4224  <>jacobmw@uber.com <mailto:jacobmw@uber.com>
