### ISSUE TITLE
installing agent class on pe master causes class conflict

### ISSUE THREAD

**Issue by micah-uber** [fnerdwq/puppet-omd#3]
Using puppet enterprise 3.7

Declare the omd:client class to the default group. When puppet runs on the master the following error is shown.

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: File[/opt/staging] is already declared in file /etc/puppetlabs/puppet/environments/production/modules/staging/manifests/init.pp:28; cannot redeclare at /opt/puppet/share/puppet/modules/pe_staging/manifests/init.pp:25 on node puppet-master01.corp.uber.internal
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by fnerdwq** [comment]
Could this be realted to?
https://tickets.puppetlabs.com/browse/ENTERPRISE-258a

It looks like: The `pe_staging` Module uses the same path `/opt/staging` like the `nanliu-staging` module used here. One fix would be to patch the `nanliu-staging` module as written in the link above, of to patch this `omd` module to use `pe_staging`.

I'm not using PE so the latter is not straightforward for me. I think it could be just replacing `staging {...: }` in `client/install.pp` by `pe_staging {...:}` wrapped in a conditional (if both staging modules use the same API) but I cannot test here. I don't have acces to the `pe_staging`s code.

**Comment by micah-uber** [comment]
I would be more than willing to test for you.

Also, a 10 node trial of PE is free.

**Comment by fnerdwq** [comment]
Since this is more related to the two staging modules, why don't you try https://github.com/nanliu/puppet-staging/pull/38/files? This seem a cleaner way of handling this, don't you think?
It's already merged into the latest forge version. Are you using a recent version of the staging module?

Yes, I know about the trial version, but I don't have a box around for a 'vagrant up'.

**Comment by micah-uber** [comment]
That is very weird.... I was using the forge version and it gave that error. I removed and reinstalled all of the modules related to omd and it works now. I have another issue that I am running into but will file this in a separate ticket.

**Comment by micah-uber** [comment]
So... My bad on this... I ran the agent install on a different box from the puppet master. If I run this on the puppet master I still get the issue.

**Comment by micah-uber** [comment]
And I am sorry for spamming your inbox... I actually made a comment on his change and will submit a issue report to the staging module.
