### ISSUE TITLE
just including omd:client is not exporting client automatically

### ISSUE THREAD

**Issue by micah-uber** [fnerdwq/puppet-omd#4]
I am getting the following error when installing the agent.

Error: Failed to apply catalog: Validation of Exec[check_mk inventorize hostname.internal for site default] failed: 'su - default -c 'check_mk -I hostname.internal'' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppetlabs/puppet/environments/production/modules/omd/manifests/host/export.pp:32
Wrapped exception:
'su - default -c 'check_mk -I hostname.internal'' is not qualified and no path was specified. Please qualify the command or specify a path.

**Comment by fnerdwq** [comment]
Can you try the fix in branch ``bug/#4``

**Comment by micah-uber** [comment]
Fixes that but now get:

Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Could not retrieve fact='apt_updates', resolution='<anonymous>': can't convert nil into Integer
Could not retrieve fact='apt_security_updates', resolution='<anonymous>': can't convert nil into Integer
Info: Caching catalog for hostname.internal
Info: Applying configuration version '1422300691'
Notice: /Stage[main]/Omd::Client::Install/Staging::File[check-mk-agent_1.2.4p5-1_all.deb]/Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb]/returns:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Notice: /Stage[main]/Omd::Client::Install/Staging::File[check-mk-agent_1.2.4p5-1_all.deb]/Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb]/returns:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0-1_all.deb]/Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb]/returns: 
Notice: /Stage[main]/Omd::Client::Install/Staging::File[check-mk-agent_1.2.4p5-1_all.deb]/Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb]/returns: curl: (22) The requested URL returned error: 404
Error: curl  -f -L -o /opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb http://mathias-kettner.de/download/check-mk-agent_1.2.4p5-1_all.deb returned 22 instead of one of [0]
Error: /Stage[main]/Omd::Client::Install/Staging::File[check-mk-agent_1.2.4p5-1_all.deb]/Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb]/returns: change from notrun to 0 failed: curl  -f -L -o /opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb http://mathias-kettner.de/download/check-mk-agent_1.2.4p5-1_all.deb returned 22 instead of one of [0]
Notice: /Package[check_mk-agent]: Dependency Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb] has failures: true
Warning: /Package[check_mk-agent]: Skipping because of failed dependencies
Notice: /Stage[main]/Omd::Client::Config/Xinetd::Service[check_mk]/File[/etc/xinetd.d/check_mk]: Dependency Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb] has failures: true
Warning: /Stage[main]/Omd::Client::Config/Xinetd::Service[check_mk]/File[/etc/xinetd.d/check_mk]: Skipping because of failed dependencies
Notice: /Stage[main]/Xinetd/Service[xinetd]: Dependency Exec[/opt/staging/omd/check-mk-agent_1.2.4p5-1_all.deb] has failures: true
Warning: /Stage[main]/Xinetd/Service[xinetd]: Skipping because of failed dependencies
Notice: Finished catalog run in 4.02 seconds

**Comment by fnerdwq** [comment]
The current Debian package ist ``check-mk-agent_1.2.4p5-2_all.deb`` so you should set ``omd::client::check_mk_version`` to ``1.2.4p5-2``.

Problem, I asked the Kettner Team to change (no response yet) to always create a 'latest' link for the agent.
