### ISSUE TITLE
mrpe error

### ISSUE THREAD

**Issue by micah-uber** [fnerdwq/puppet-omd#6]
Error: Could not set 'file' on ensure: No such file or directory - /etc/check_mk/mrpe.cfg20150126-22559-1ad5p9t.lock at 179:/etc/puppetlabs/puppet/environments/production/modules/concat/manifests/init.pp
Error: Could not set 'file' on ensure: No such file or directory - /etc/check_mk/mrpe.cfg20150126-22559-1ad5p9t.lock at 179:/etc/puppetlabs/puppet/environments/production/modules/concat/manifests/init.pp
Wrapped exception:
No such file or directory - /etc/check_mk/mrpe.cfg20150126-22559-1ad5p9t.lock
Error: /Stage[main]/Omd::Client::Checks::Config/Concat[/etc/check_mk/mrpe.cfg]/File[/etc/check_mk/mrpe.cfg]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /etc/check_mk/mrpe.cfg20150126-22559-1ad5p9t.lock at 179:/etc/puppetlabs/puppet/environments/production/modules/concat/manifests/init.pp

**Comment by fnerdwq** [comment]
Does the directory ``/etc/check_mk`` exist?
Are you using the latest github version? Actually I fixed this problem there - I thought.

**Comment by micah-uber** [comment]
That directory does not exist.


--
Micah Figone

Senior Systems Engineer
Uber

**Comment by fnerdwq** [comment]
This is fixed in the current HEAD. I suppose you are using the lastet Forge version?

**Comment by micah-uber** [comment]
Yes. Using the latest forge version

**Comment by fnerdwq** [comment]
So please use the latest github version ;-)
