### ISSUE TITLE
errors on checkmk dashboard

### ISSUE THREAD

**Issue by micah-uber** [fnerdwq/puppet-omd#7]
http://comments.gmane.org/gmane.network.nagios.checkmk/6656

apt-get install apache2-mpm-prefork is supposed to fix this but it does not in this instance.

**Comment by fnerdwq** [comment]
I didn't include a dependency on the apche module, therefore I don't think this dependency should be taken care of here -> would be somehtin for the rpm/deb.

BTW: I put a new version on the forge.
