### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by emccormickva** [fnerdwq/puppet-omd#9]
Hello I'm getting the following error attempting to install just including the omd::server class with no extra configuration options set

Unknown function query_nodes at /etc/puppet/environments/rwdc1prod/modules/omd/manifests/site/config_hosts.pp:28

Am I missing a dependency somewhere?

Thanks,
Erik

**Comment by fnerdwq** [comment]
Hi Erik,
you need the Puppetdbquery Module from the Forge https://forge.puppetlabs.com/dalen/puppetdbquery, see dependecy in ``metadata.json``
```
 {"name":"dalen/puppetdbquery","version_requirement":">= 1.5.2 <2.0.0"}
```

Bye
Frederik
